{
 "title": "PostgreSQL Tables",
 "description": "Dashboard for detailed table details of PostgreSQL.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "operator",
    "label": "Instance",
    "query": "label_values(kube_statefulset_created{statefulset=~\".*-keeper\"}, statefulset)"
   },
   { "name": "instance", "label": "Instance", "query": "label_values(pg_up, pod)" },
   {
    "name": "db",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{datname!~\"template.*\", pod=\"$instance\"},datname)"
   },
   {
    "name": "table",
    "label": "Table",
    "query": "label_values(pg_stat_user_tables_n_live_tup, relname)"
   }
  ]
 },
 "panels": [
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(pg_database_size_bytes{pod=\"$instance\", datname=\"$db\"})",
     "legendFormat": "DB Size"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max (irate(pg_stat_database_xact_commit{pod=\"$instance\", datname=\"$db\"}[5m]))",
     "legendFormat": "commits"
    },
    {
     "expr": "max(irate(pg_stat_database_xact_rollback{pod=\"$instance\", datname=\"$db\"}[5m]))",
     "legendFormat": "rollbacks"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Rows" }
   ],
   "targets": [
    {
     "expr": "max(irate(pg_stat_database_tup_inserted{pod=\"$instance\", datname=\"$db\"}[5m]))",
     "legendFormat": "INSERT"
    },
    {
     "expr": "max(irate(pg_stat_database_tup_updated{pod=\"$instance\", datname=\"$db\"}[5m]))",
     "legendFormat": "UPDATE"
    },
    {
     "expr": "max(irate(pg_stat_database_tup_deleted{pod=\"$instance\", datname=\"$db\"}[5m]))",
     "legendFormat": "DELETE"
    },
    {
     "expr": "max (irate(pg_stat_database_tup_fetched{pod=\"$instance\", datname=\"$db\"}[5m]))",
     "legendFormat": "SELECT (index scan)"
    },
    {
     "expr": "max(irate(pg_stat_database_tup_returned{pod=\"$instance\", datname=\"$db\"}[5m]))",
     "legendFormat": "SELECT (table scan)"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (state)(pg_stat_activity_count{pod=\"$instance\", datname=\"$db\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(pg_stat_database_blks_hit{pod=\"$instance\", datname=\"$db\"} / (pg_stat_database_blks_read{pod=\"$instance\", datname=\"$db\"} + pg_stat_database_blks_hit{pod=\"$instance\", datname=\"$db\"}))",
     "legendFormat": "Cache Hit Rate"
    }
   ]
  },
  {
   "title": "Longest Transaction",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (state)(pg_stat_activity_max_tx_duration{pod=\"$instance\", datname=\"$db\"})",
     "legendFormat": "max_tx_duration [{{state}}]"
    }
   ]
  },
  {
   "title": "Lock Tables",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (mode)(pg_locks_count{pod=\"$instance\", datname=\"$db\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Temp File",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(irate(pg_stat_database_temp_bytes{pod=\"$instance\", datname=\"$db\"}[5m]))",
     "legendFormat": "Temp Bytes"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(irate(pg_stat_database_conflicts{pod=\"$instance\", datname=\"$db\"}[5m]))",
     "legendFormat": "conflicts"
    },
    {
     "expr": "max(irate(pg_stat_database_deadlocks{pod=\"$instance\", datname=\"$db\"}[5m]))",
     "legendFormat": "deadlocks"
    }
   ]
  },
  { "title": "Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Estimated Row Counts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max (pg_stat_user_tables_n_live_tup{pod=\"$instance\", datname=\"$db\", relname=\"$table\"})",
     "legendFormat": "Est. Live Rows"
    },
    {
     "expr": "max (pg_stat_user_tables_n_dead_tup{pod=\"$instance\", datname=\"$db\", relname=\"$table\"})",
     "legendFormat": "Est. Dead Rows"
    }
   ]
  },
  {
   "title": "Scans and Row Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max (irate(pg_stat_user_tables_idx_scan{pod=\"$instance\", datname=\"$db\", relname=\"$table\"}[5m]))",
     "legendFormat": "Index Scans"
    },
    {
     "expr": "max (irate(pg_stat_user_tables_idx_tup_fetch{pod=\"$instance\", datname=\"$db\", relname=\"$table\"}[5m]))",
     "legendFormat": "Rows Fetched by index scan"
    },
    {
     "expr": "max (irate(pg_stat_user_tables_seq_scan{pod=\"$instance\", datname=\"$db\", relname=\"$table\"}[5m]))",
     "legendFormat": "Sequential Scans"
    },
    {
     "expr": "max (irate(pg_stat_user_tables_seq_tup_read{pod=\"$instance\", datname=\"$db\", relname=\"$table\"}[5m]))",
     "legendFormat": "Rows Read by sequential scan"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max (irate(pg_stat_user_tables_n_tup_ins{pod=\"$instance\", datname=\"$db\", relname=\"$table\"}[5m]))",
     "legendFormat": "Insert"
    },
    {
     "expr": "max (irate(pg_stat_user_tables_n_tup_upd{pod=\"$instance\", datname=\"$db\", relname=\"$table\"}[5m]))",
     "legendFormat": "Update"
    },
    {
     "expr": "max (irate(pg_stat_user_tables_n_tup_hot_upd{pod=\"$instance\", datname=\"$db\", relname=\"$table\"}[5m]))",
     "legendFormat": "Hot Update"
    },
    {
     "expr": "max (irate(pg_stat_user_tables_n_tup_del{pod=\"$instance\", datname=\"$db\", relname=\"$table\"}[5m]))",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "Row Modifications since last Analyse",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max (pg_stat_user_tables_n_mod_since_analyze{pod=\"$instance\", datname=\"$db\", relname=\"$table\"})",
     "legendFormat": "Modifications"
    }
   ]
  },
  {
   "title": "Blocks Read",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max by (relname)(irate(pg_statio_user_tables_heap_blks_read{pod=\"$instance\", datname=\"$db\", relname=\"$table\"}[1m]))",
     "legendFormat": "Blocks read from disk"
    },
    {
     "expr": "max by (relname)(irate(pg_statio_user_tables_heap_blks_hit{pod=\"$instance\", datname=\"$db\", relname=\"$table\"}[1m]))",
     "legendFormat": "Block reads from buffer"
    },
    {
     "expr": "max by (relname)(irate(pg_statio_user_tables_idx_blks_read{pod=\"$instance\", datname=\"$db\", relname=\"$table\"}[1m]))",
     "legendFormat": "Index blocks read from disk"
    },
    {
     "expr": "max by (relname)(irate(pg_statio_user_tables_idx_blks_hit{pod=\"$instance\", datname=\"$db\", relname=\"$table\"}[1m]))",
     "legendFormat": "Index blocks read from buffer"
    },
    {
     "expr": "max by (relname)(irate(pg_statio_user_tables_toast_blks_read{pod=\"$instance\", datname=\"$db\", relname=\"$table\"}[1m]))",
     "legendFormat": "Toast blocks read from disk"
    },
    {
     "expr": "max by (relname)(irate(pg_statio_user_tables_toast_blks_hit{pod=\"$instance\", datname=\"$db\", relname=\"$table\"}[1m]))",
     "legendFormat": "Toast blocks read from buffer"
    },
    {
     "expr": "max by (relname)(irate(pg_statio_user_tables_tidx_blks_read{pod=\"$instance\", datname=\"$db\", relname=\"$table\"}[1m]))",
     "legendFormat": "Toast index blocks read from disk"
    },
    {
     "expr": "max by (relname)(irate(pg_statio_user_tables_tidx_blks_hit{pod=\"$instance\", datname=\"$db\", relname=\"$table\"}[1m]))",
     "legendFormat": "Toast index blocks read from buffer"
    }
   ]
  },
  {
   "title": "Analysis & Vacuum",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max by (relname)(irate(pg_stat_user_tables_autoanalyze_count{pod=\"$instance\", datname=\"$db\", relname=\"$table\"}[1m]))",
     "legendFormat": "Autoanalysis"
    },
    {
     "expr": "max by (relname)(irate(pg_stat_user_tables_autovacuum_count{pod=\"$instance\", datname=\"$db\", relname=\"$table\"}[1m]))",
     "legendFormat": "Autovacuum"
    },
    {
     "expr": "max by (relname)(irate(pg_stat_user_tables_analyze_count{pod=\"$instance\", datname=\"$db\", relname=\"$table\"}[1m]))",
     "legendFormat": "Analysis"
    },
    {
     "expr": "max by (relname)(irate(pg_stat_user_tables_vacuum_count{pod=\"$instance\", datname=\"$db\", relname=\"$table\"}[5m]))",
     "legendFormat": "Vacuum"
    }
   ]
  }
 ]
}