{
 "title": "PostgreSQL Statistics",
 "description": "Dashboard for PostgreSQL Statistics.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "operator",
    "label": "Instance",
    "query": "label_values(kube_statefulset_created{statefulset=~\".*-keeper\"}, statefulset)"
   },
   { "name": "instance", "label": "Instance", "query": "label_values(pg_up, pod)" }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Master",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "stolon_keeper_local_role{pod=~\"$operator-keeper.*\", role=\"master\"} == 1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Keeper Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_statefulset_replicas{statefulset=\"$operator-keeper\"}"
    }
   ]
  },
  {
   "title": "Proxy nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=\"$operator-proxy\"}"
    }
   ]
  },
  {
   "title": "Sentinel nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=\"$operator-sentinel\"}"
    }
   ]
  },
  {
   "title": "Unavailable Keeper Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_statefulset_replicas{statefulset=\"$operator-keeper\"} - kube_statefulset_status_replicas_ready{statefulset=\"$operator-keeper\"}"
    }
   ]
  },
  {
   "title": "Total Database Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pg_database_size_bytes{pod=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Write Ahead Log Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "TODO" }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Postgres Version",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "expr": "pg_static{pod=\"$instance\"}",
       "legendFormat": "{{short_version}}"
      }
     ]
    },
    {
     "title": "Max Connections",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "pg_settings_max_connections{pod=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max Worker Processes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "pg_settings_max_worker_processes{pod=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Effective Cache",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 5 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_effective_cache_size_bytes{pod=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max WAL Size",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 14, "y": 5 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_max_wal_size_bytes{pod=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Random Page Cost",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_random_page_cost{pod=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Seq Page Cost",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "pg_settings_seq_page_cost" }
     ]
    },
    {
     "title": "Shared Buffers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 8 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_shared_buffers_bytes{pod=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Maintenance Work Mem",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 8 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_maintenance_work_mem_bytes{pod=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Work Mem",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 14, "y": 8 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_work_mem_bytes{pod=\"$instance\"}"
      }
     ]
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Database Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by(datname)(pg_database_size_bytes{pod=\"$instance\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Index Scans",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (datname)(irate(pg_stat_user_tables_idx_scan{pod=\"$instance\"}[5m]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Live Rows",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (datname)(pg_stat_user_tables_n_live_tup{pod=\"$instance\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Sequential Scans",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (datname)(irate(pg_stat_user_tables_seq_scan{pod=\"$instance\"}[5m]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Dead Rows",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (datname)(pg_stat_user_tables_n_dead_tup{pod=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Row Modifications since last Analyse",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (datname)(pg_stat_user_tables_n_mod_since_analyze{pod=\"$instance\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Connection / Transaction Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state)(pg_stat_activity_count{pod=\"$instance\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate(pg_stat_database_xact_commit{pod=\"$instance\"}[5m]))",
     "legendFormat": "commits"
    },
    {
     "expr": "sum(irate(pg_stat_database_xact_rollback{pod=\"$instance\"}[5m]))",
     "legendFormat": "rollbacks"
    }
   ]
  },
  {
   "title": "Read Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Rows" }
   ],
   "targets": [
    {
     "expr": "sum (irate(pg_stat_database_tup_fetched{pod=\"$instance\"}[5m]))",
     "legendFormat": "Rows fetched"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_returned{pod=\"$instance\"}[5m]))",
     "legendFormat": "Rows returned"
    }
   ]
  },
  {
   "title": "Change Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Rows" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_inserted{pod=\"$instance\"}[5m]))",
     "legendFormat": "INSERT"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_updated{pod=\"$instance\"}[5m]))",
     "legendFormat": "UPDATE"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_deleted{pod=\"$instance\"}[5m]))",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Longest Transaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (state)(pg_stat_activity_max_tx_duration{pod=\"$instance\"})",
     "legendFormat": "max_tx_duration [{{state}}]"
    }
   ]
  },
  { "title": "misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Buffers (bgwriter)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(irate(pg_stat_bgwriter_buffers_backend{pod=\"$instance\"}[5m]))",
     "legendFormat": "backend"
    },
    {
     "expr": "max(irate(pg_stat_bgwriter_buffers_alloc{pod=\"$instance\"}[5m]))",
     "legendFormat": "alloc"
    },
    {
     "expr": "max(irate(pg_stat_bgwriter_buffers_backend_fsync{pod=\"$instance\"}[5m]))",
     "legendFormat": "fsync"
    },
    {
     "expr": "max(irate(pg_stat_bgwriter_buffers_checkpoint{pod=\"$instance\"}[5m]))",
     "legendFormat": "checkpoint"
    },
    {
     "expr": "max(irate(pg_stat_bgwriter_buffers_clean{pod=\"$instance\"}[5m]))",
     "legendFormat": "clean"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_conflicts{pod=\"$instance\"}[5m]))",
     "legendFormat": "conflicts"
    },
    {
     "expr": "sum(irate(pg_stat_database_deadlocks{pod=\"$instance\"}[5m]))",
     "legendFormat": "deadlocks"
    }
   ]
  },
  {
   "title": "Lock Tables",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(pg_locks_count{pod=\"$instance\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Temp File",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 55 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_temp_bytes{pod=\"$instance\"}[5m]))",
     "legendFormat": "Temp Bytes"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(irate(pg_stat_bgwriter_checkpoint_write_time{pod=\"$instance\"}[5m]))",
     "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
    },
    {
     "expr": "max(irate(pg_stat_bgwriter_checkpoint_sync_time{pod=\"$instance\"}[5m]))",
     "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
    }
   ]
  },
  {
   "title": "Replication Log Position",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max by (client_addr) (pg_stat_replication_pg_current_wal_lsn_bytes{pod=\"$instance\"})",
     "legendFormat": "Target {{client_addr}}"
    }
   ]
  },
  {
   "title": "Replication Log Difference",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max by (client_addr) (pg_stat_replication_pg_wal_lsn_diff{pod=\"$instance\"})",
     "legendFormat": "Target {{client_addr}}"
    }
   ]
  }
 ]
}