apiVersion: kudo.dev/v1beta1
kind: Instance
metadata:
  name: postgres
status:
  planStatus:
    deploy:
      status: COMPLETE
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-keeper
status:
  readyReplicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-proxy
status:
  readyReplicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-sentinel
status:
  readyReplicas: 2
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-proxy-svc-ext
spec:
  ports:
    - nodePort: 30001