apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Name }}-init
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: {{ $.Name }}-sa
      restartPolicy: Never
      containers:
        - name: init
          image: {{ $.Params.STOLON_DOCKER_IMAGE }}
          imagePullPolicy: {{ $.Params.STOLON_DOCKER_IMAGE_PULL_POLICY }}
          command:
            - bash
            - -c
          args:
            - stolonctl --cluster-name={{ $.Params.CLUSTER_NAME }} --store-backend=kubernetes --kube-resource-kind=configmap init --yes -f /cluster-spec/cluster-spec.json;
              while :; do echo "Waiting for service to be ready..."; sleep 3; pg_isready --host postgres-proxy-svc --port {{ $.Params.SQL_PORT }} && break; done;
          volumeMounts:
            - mountPath: /cluster-spec
              name: cluster-spec
      volumes:
        - name: cluster-spec
          configMap:
            name: {{ $.Name }}-stolon-spec
            defaultMode: 0755