# This is an example and generic rbac role definition for stolon. It could be
# fine tuned and split per component.
# The required permission per component should be:
# keeper/proxy/sentinel: update their own pod annotations
# sentinel/stolonctl: get, create, update configmaps
# sentinel/stolonctl: list components pods
# sentinel/stolonctl: get components pods annotations

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: "{{ $.Name }}-sa-role"
  namespace: {{ $.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - events
    verbs:
      - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Name }}-sa
  namespace: {{ $.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ $.Name }}-sa-rolebinding
  namespace: {{ $.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $.Name }}-sa-role
  namespace: {{ $.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ $.Name }}-sa
    namespace: {{ $.Namespace }}