apiVersion: v1
kind: Service
metadata:
  name: {{ $.Name }}-stolon-monitoring
  labels:
    kudo.dev/servicemonitor: "true"
spec:
  ports:
    - port: {{ .Params.PROMETHEUS_EXPORTER_PORT }}
      name: prometheus-exporter-port
      targetPort: {{ $.Params.INTERNAL_STOLON_METRICS_EXPORTER_PORT }}
  selector:
    stolon-cluster: {{ $.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Name }}-pg-monitoring
  labels:
    kudo.dev/servicemonitor: "true"
spec:
  ports:
    - port: {{ .Params.PROMETHEUS_EXPORTER_PORT }}
      name: prometheus-exporter-port
      targetPort: {{ $.Params.INTERNAL_PG_EXPORTER_PORT }}
  selector:
    component: stolon-keeper
    stolon-cluster: {{ $.Name }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $.Name }}-monitor
  namespace: {{ $.Namespace }}
  labels:
    app: prometheus-operator
    release: prometheus-kubeaddons
spec:
  endpoints:
    - interval: 30s
      port: prometheus-exporter-port
  namespaceSelector:
    matchNames:
      - {{ $.Namespace }}
  selector:
    matchLabels:
      kudo.dev/instance: {{ $.Name }}
      kudo.dev/servicemonitor: "true"
