apiVersion: v1
kind: Service
metadata:
  name: {{ $.Name }}-proxy-svc-ext-lb
spec:
  type: LoadBalancer
  ports:
    - port: {{ $.Params.SQL_PORT }}
      targetPort: 5432
  selector:
    component: stolon-proxy
    stolon-cluster: {{ $.Name }}
