apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Name }}-proxy
spec:
  replicas: {{ $.Params.PROXY_NODES }}
  selector:
    matchLabels:
      component: stolon-proxy
      stolon-cluster: {{ $.Params.CLUSTER_NAME }}
  template:
    metadata:
      labels:
        component: stolon-proxy
        stolon-cluster: {{ $.Params.CLUSTER_NAME }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ $.Params.INTERNAL_STOLON_METRICS_EXPORTER_PORT }}"
    spec:
      serviceAccountName: "{{ $.Name }}-sa"
      containers:
        - name: stolon-proxy
          image: {{ $.Params.STOLON_DOCKER_IMAGE }}
          imagePullPolicy: {{ $.Params.STOLON_DOCKER_IMAGE_PULL_POLICY }}
          command:
            - "/bin/bash"
            - "-ec"
            - |
              exec gosu stolon stolon-proxy
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STPROXY_CLUSTER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['stolon-cluster']
            - name: STPROXY_STORE_BACKEND
              value: "kubernetes"
            - name: STPROXY_KUBE_RESOURCE_KIND
              value: "configmap"
            - name: STPROXY_LISTEN_ADDRESS
              value: "0.0.0.0"
            {{ if eq $.Params.PROMETHEUS_EXPORTER_ENABLED "true" }}
            - name: STPROXY_METRICS_LISTEN_ADDRESS
              value: "0.0.0.0:{{ $.Params.INTERNAL_STOLON_METRICS_EXPORTER_PORT }}"
            {{ end }}
            {{ if eq $.Params.PROXY_DEBUG "true" }}
            - name: STPROXY_DEBUG
              value: "true"
            {{ end }}
          resources:
            requests:
              memory: "{{ $.Params.PROXY_MEM_MIB }}Mi"
              cpu: "{{ $.Params.PROXY_CPU_MC }}m"
            limits:
              memory: "{{ $.Params.PROXY_MEM_LIMIT_MIB }}Mi"
              cpu: "{{ $.Params.PROXY_CPU_LIMIT_MC }}m"
          ports:
            - containerPort: 5432
            {{ if eq $.Params.PROMETHEUS_EXPORTER_ENABLED "true" }}
            - containerPort: {{ $.Params.INTERNAL_STOLON_METRICS_EXPORTER_PORT }}
            {{ end }}
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            timeoutSeconds: 5
