apiVersion: v1
kind: Service
metadata:
  name: {{ $.Name }}-proxy-svc-ext
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: {{ $.Params.EXTERNAL_NODE_PORT }}
  selector:
    component: stolon-proxy
    stolon-cluster: {{ $.Params.CLUSTER_NAME }}
