apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Name }}-stolon-spec
  namespace: {{ $.Namespace }}
data:
  cluster-spec.json: |
    {
      "initMode": "new",
      "newConfig": {
        "dataChecksums": false
      },
      "synchronousReplication": {{ $.Params.PG_SYNCHRONOUS_REPLICATION }},
      "proxyTimeout": "{{ $.Params.STOLON_PROXY_TIMEOUT }}",
      "proxyCheckInterval": "{{ $.Params.STOLON_PROXY_CHECK_INTERVAL }}",
      "failInterval": "{{ $.Params.STOLON_FAIL_INTERVAL }}",
      "sleepInterval":  "{{ $.Params.STOLON_SLEEP_INTERVAL }}",
      "pgParameters": {
      {{- if .Params.POSTGRES_ADDITIONAL_SETTINGS }}
      {{ $max := len $.Params.POSTGRES_ADDITIONAL_SETTINGS }}
      {{ $max = sub $max 1 }}
      {{ range $i, $setting := $.Params.POSTGRES_ADDITIONAL_SETTINGS -}}
         "{{ $setting.key }}": "{{ $setting.val }}"{{ if not (eq $i $max) }},{{end}}
      {{ end }}
      {{ end }}
      }
    }
