apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Name }}-keeper
spec:
  serviceName: "{{ $.Name }}-keeper"
  replicas: {{ $.Params.KEEPER_NODES }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      component: stolon-keeper
      stolon-cluster: {{ $.Params.CLUSTER_NAME }}
  template:
    metadata:
      labels:
        component: stolon-keeper
        stolon-cluster: {{ $.Params.CLUSTER_NAME }}
        {{ if eq .Params.PROMETHEUS_EXPORTER_ENABLED "true" }}
        kudo.dev/servicemonitor: "true"
        {{ end }}
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: "{{ $.Name }}-sa"
      terminationGracePeriodSeconds: 10
      containers:
        - name: stolon-keeper
          image: {{ $.Params.STOLON_DOCKER_IMAGE }}
          imagePullPolicy: {{ $.Params.STOLON_DOCKER_IMAGE_PULL_POLICY }}
          command:
            - "/bin/bash"
            - "-ec"
            - |
              # Generate our keeper uid using the pod index
              IFS='-' read -ra ADDR <<< "$(hostname)"
              export STKEEPER_UID="keeper${ADDR[-1]}"
              export POD_IP=$(hostname -i)
              export STKEEPER_PG_LISTEN_ADDRESS=$POD_IP
              export STOLON_DATA=/stolon-data
              chown stolon:stolon $STOLON_DATA
              exec gosu stolon stolon-keeper --data-dir $STOLON_DATA
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STKEEPER_CLUSTER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['stolon-cluster']
            - name: STKEEPER_STORE_BACKEND
              value: "kubernetes"
            - name: STKEEPER_KUBE_RESOURCE_KIND
              value: "configmap"
            - name: STKEEPER_PG_REPL_USERNAME
              value: "repluser"
              # Or use a password file like in the below supersuser password
            - name: STKEEPER_PG_REPL_PASSWORD
              value: "replpassword"
            - name: STKEEPER_PG_SU_USERNAME
              value: "stolon"
            - name: STKEEPER_PG_SU_PASSWORDFILE
              value: "/etc/secrets/stolon/password"
            {{ if eq $.Params.PROMETHEUS_EXPORTER_ENABLED "true" }}
            - name: STKEEPER_METRICS_LISTEN_ADDRESS
              value: "0.0.0.0:8080"
            {{ end }}
            {{ if eq $.Params.KEEPER_DEBUG "true" }}
            - name: STKEEPER_DEBUG
              value: "true"
            {{ end }}
          resources:
            requests:
              memory: "{{ $.Params.KEEPER_MEM_MIB }}Mi"
              cpu: "{{ $.Params.KEEPER_CPU_MC }}m"
            limits:
              memory: "{{ $.Params.KEEPER_MEM_LIMIT_MIB }}Mi"
              cpu: "{{ $.Params.KEEPER_CPU_LIMIT_MC }}m" 
          ports:
            - containerPort: 5432
            {{ if eq $.Params.PROMETHEUS_EXPORTER_ENABLED "true" }}
            - containerPort: 8080
            {{ end }}
          volumeMounts:
            - mountPath: /stolon-data
              name: data
            - mountPath: /etc/secrets/stolon
              name: stolon
        {{ if eq $.Params.PROMETHEUS_EXPORTER_ENABLED "true" }}
        - name: prometheus-exporter
          image: {{ $.Params.PROMETHEUS_EXPORTER_DOCKER_IMAGE }}
          imagePullPolicy: {{ $.Params.PROMETHEUS_EXPORTER_DOCKER_IMAGE_PULL_POLICY }}
          resources:
            requests:
              memory: "{{ $.Params.PROMETHEUS_EXPORTER_MEM_MIB }}Mi"
              cpu: "{{ $.Params.PROMETHEUS_EXPORTER_CPU_MC }}m"
            limits:
              memory: "{{ $.Params.PROMETHEUS_EXPORTER_MEM_LIMIT_MIB }}Mi"
              cpu: "{{ $.Params.PROMETHEUS_EXPORTER_CPU_LIMIT_MC }}m"
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://stolon:password1@{{ $.Name }}-keeper-0:5432/postgres?sslmode=disable"
          ports:
            - containerPort: 9187
        {{ end }}
      volumes:
        - name: stolon
          secret:
            secretName: stolon
  # Define your own volumeClaimTemplate. This example uses dynamic PV provisioning with a storage class named "standard" (so it will works by default with minikube)
  # In production you should use your own defined storage-class and configure your persistent volumes (statically or dynamically using a provisioner, see related k8s doc).
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          volume.alpha.kubernetes.io/storage-class: standard
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ $.Params.KEEPER_DISK_SIZE_GIB }}Gi