apiVersion: v1
kind: Service
metadata:
  name: {{ $.Name }}-proxy-svc
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    component: stolon-proxy
    stolon-cluster: {{ $.Params.CLUSTER_NAME }}
