apiVersion: kudo.dev/v1beta1
parameters:

  - name: KEEPER_NODES
    description: Number of Stolon Keeper nodes
    default: 2
  - name: PROXY_NODES
    description: Number of Stolon Proxy nodes
    default: 2
  - name: SENTINEL_NODES
    default: 2

  - name: CLUSTER_NAME
    description: The name of this Postgres Stolon Cluster
    default: kube-stolon

  - name: STOLON_DOCKER_IMAGE
    description: TODO
    default: "sorintlab/stolon:master-pg10"

  - name: STOLON_DOCKER_IMAGE_PULL_POLICY
    description: TODO
    default: Always

  - name: EXTERNAL_SERVICE
    description: TODO
    default: false

  - name: EXTERNAL_NODE_PORT
    description: TODO
    default: 30001

  - name: SQL_PORT
    description: TODO
    default: 5432

  - name: CREDENTIALS_SECRET_NAME
    description: "The credentials secret that contains usernames and passwords for a superuser and a replication user"
    required: true
    default: "set-me"

  ################################################################################
  ############################### Postgres settings ##############################
  ################################################################################

  - name: POSTGRES_ADDITIONAL_SETTINGS
    description: "Custom postgres settings that are not exposed otherwise"
    type: array

  - name: PG_SYNCHRONOUS_REPLICATION
    description: TODO
    default: false

  ################################################################################
  ############################### Keeper settings ################################
  ################################################################################

  - name: KEEPER_CPU_MC
    description: "CPU request (in millicores) for the Stolon Keeper containers."
    default: "500"

  - name: KEEPER_CPU_LIMIT_MC
    description: "CPU limit (in millicores) for the Stolon Keeper containers."
    default: "750"

  - name: KEEPER_MEM_MIB
    description: "Memory request (in MiB) for the Stolon Keeper containers."
    default: "1024"

  - name: KEEPER_MEM_LIMIT_MIB
    description: "Memory limit (in MiB) for the Stolon Keeper containers."
    default: "1200"

  - name: KEEPER_DISK_SIZE_GIB
    description: "Disk size (in GiB) for the Stolon Keeper containers."
    default: "20"

  - name: KEEPER_DEBUG
    description: TODO
    default: true

  - name: STOLON_SLEEP_INTERVAL
    default: 5s

  - name: STOLON_FAIL_INTERVAL
    default: 20s

  - name: STOLON_PROXY_CHECK_INTERVAL
    default: 5s

  - name: STOLON_PROXY_TIMEOUT
    default: 15s

  ################################################################################
  ############################### Proxy settings #################################
  ################################################################################

  - name: PROXY_CPU_MC
    description: "CPU request (in millicores) for the Stolon Proxy containers."
    default: "100"

  - name: PROXY_CPU_LIMIT_MC
    description: "CPU limit (in millicores) for the Stolon Proxy containers."
    default: "120"

  - name: PROXY_MEM_MIB
    description: "Memory request (in MiB) for the Stolon Proxy containers."
    default: "20"

  - name: PROXY_MEM_LIMIT_MIB
    description: "Memory limit (in MiB) for the Stolon Proxy containers."
    default: "40"

  - name: PROXY_DEBUG
    description: TODO
    default: true

  ################################################################################
  ############################### Sentinel settings ##############################
  ################################################################################

  - name: SENTINEL_CPU_MC
    description: "CPU request (in millicores) for the Stolon Sentinel containers."
    default: "100"

  - name: SENTINEL_CPU_LIMIT_MC
    description: "CPU limit (in millicores) for the Stolon Sentinel containers."
    default: "120"

  - name: SENTINEL_MEM_MIB
    description: "Memory request (in MiB) for the Stolon Sentinel containers."
    default: "20"

  - name: SENTINEL_MEM_LIMIT_MIB
    description: "Memory limit (in MiB) for the Stolon Sentinel containers."
    default: "40"

  - name: SENTINEL_DEBUG
    description: TODO
    default: true

  ################################################################################
  ######################### Prometheus exporter settings #########################
  ################################################################################

  - name: PROMETHEUS_EXPORTER_ENABLED
    description: "A toggle to enable the prometheus metrics exporter."
    default: "false"

  - name: PROMETHEUS_EXPORTER_PORT
    description: "Prometheus exporter port."
    default: "7200"

  - name: PROMETHEUS_EXPORTER_CPU_MC
    description: "CPU request (in millicores) for the Prometheus exporter containers."
    default: "100"

  - name: PROMETHEUS_EXPORTER_CPU_LIMIT_MC
    description: "CPU limit (in millicores) for the Prometheus exporter containers."
    default: "250"

  - name: PROMETHEUS_EXPORTER_MEM_MIB
    description: "Memory request (in MiB) for the Prometheus exporter containers."
    default: "50"

  - name: PROMETHEUS_EXPORTER_MEM_LIMIT_MIB
    description: "Memory limit (in MiB) for the Prometheus exporter containers."
    default: "100"

  - name: PROMETHEUS_EXPORTER_DOCKER_IMAGE
    description: "Prometheus exporter Docker image."
    default: "wrouesnel/postgres_exporter:v0.8.0"

  - name: PROMETHEUS_EXPORTER_DOCKER_IMAGE_PULL_POLICY
    description: "Prometheus exporter Docker image pull policy."
    default: "Always"

  ################################################################################
  ######################### Internal settings ####################################
  ################################################################################

  - name: INTERNAL_PG_EXPORTER_PORT
    description: "Internal container port for prometheus exporter"
    default: "9187"

  - name: INTERNAL_STOLON_METRICS_EXPORTER_PORT
    description: "Internal container port for stolon metrics export"
    default: "8080"
